# Python brush-up
The aim of this notebook is to give a brief overview of some python skills that will be useful when working with EEG data and the `MNE-python` package. 

The notebook is divided into two parts:
1. Python classes
2. Numpy basics

## 1. Python classes
Python is a programming language which allows for object-oriented programming. The basic idea, is that it is possible to combine both data and methods into a single unit (known as an object) which operate on the data.

To begin, a class must be defined, which serves as the blueprint for creating objects. 


Let's use the following example:

In [2]:
class Dog:
    def __init__(self, name, breed, age):
        self.name = name
        self.breed = breed
        self.age = age
    
    # defining methods
    def bark(self):
        print("Woof woof!")
    
    def introduce(self):
        print("My name is " + self.name + " and I am a " + self.breed + ".") 

    def birthday(self):
        self.age += 1

#### init
`__init__` is a special method in Python classes, also known as a constructor method. It is automatically called when an object of the class is created and is used to initialise the attributes of the object.

In the example class Dog, `__init__ `takes three arguments: name, breed and age. These values are passed to the method when an object of the class is created, and are used to initialise the name and breed attributes of the object.

### self
In Python, the `self` keyword is used to refer to the current instance of a class. It is used to access and modify the attributes and methods of the current object.

When a method is called on an object, the object is automatically passed as the first argument to the method. This first argument is typically named self by convention, but it can be named anything.

For example, in the the birthday method, `self.age` is used to access the age attribute of the object.

It is worth noting that when you call a method on an object, you don't need to pass the self argument, python takes care of passing it when using the syntax seen in the following code chunk. 

In [3]:
dog = Dog("Simba", "Cocker Spaniel", 3)

# using the bark method
dog.bark()

# using the introduce method
dog.introduce()

# checking the age
print(dog.age)

Woof woof!
My name is Simba and I am a Cocker Spaniel.
3


The two methods above did not change the object. However, some methods defined might change the attributes or behavior of the object. These are known as mutator methods. In the example class Dog, the birthday method is an example of a mutator method, as it changes the age attribute of the object. On the other hand, the bark and introduce methods are known as accessor methods, as they do not modify the state of the object, they only return or print information about the object.

Let's test it out!

In [4]:
print(f'Before {dog.name}s birthday, the dog was {dog.age}.')

dog.birthday()

print(f'After {dog.name}s birthday, the dog is {dog.age}.')

Before Simbas birthday, the dog was 3.
After Simbas birthday, the dog is 4.


### MNE classes

The MNE toolkit is a library for processing of electrophysiological data, such as EEG and MEG, and it provides several classes that represent different types of data. The `Raw`, `Epochs`, and `Evoked` are examples of these classes and all have associated methods that can be used to manipulate and analyse the data they represent.

* The `Raw` class is used to represent continuous data, such as raw EEG recordings. It includes methods for filtering, dropping bad channels, plotting, resampling, and so forth.

* The `Epochs` class contains data that has been segmented into "epochs" or time windows of interest. It includes methods for averaging, baseline correction, and plotting.

* The `Evoked` class is used to represent the average response to a specific stimulus or condition. It includes methods for plotting and statistics.


Some methods of the classes modify the object in place such as the Raw.filter() method. This means that the object is modified and no new object is returned. This is different from the Epochs.average() method which returns a new Evoked object. By modifying in place memory is saved as the original object is not copied.

## 2. Numpy basics
In this section we will cover some basic numpy operations that will be useful when working with EEG data. As EEG epoched data has three dimensions (time, channels, trials), it can be useful to have an intuitive understanding of how to manipulate these dimensions.

In [1]:
import numpy as np

We start by defining an array of random numbers, which we will use to illustrate the different operations. Let's pretend it is epoched EEG data from 60 sensors, 200 time points, and 50 trials

In [6]:
# create a 3d array 
arr = np.random.random((50, 60, 200)) # trial, sensor, time

# check that the shape is what we expect
print(arr.shape)

# print the array
print(arr)

(50, 60, 200)
[[[0.05017391 0.19390006 0.57630661 ... 0.75306148 0.61462096 0.59377528]
  [0.25452629 0.92540862 0.96634074 ... 0.13366413 0.53700582 0.7344159 ]
  [0.05557161 0.54621973 0.58468124 ... 0.38833852 0.55875184 0.32331538]
  ...
  [0.19670757 0.6832596  0.17194067 ... 0.30653204 0.65660018 0.77513761]
  [0.16486988 0.61006166 0.89753683 ... 0.51630285 0.70822291 0.50822757]
  [0.92205561 0.05835196 0.10319847 ... 0.23737253 0.80887616 0.10336871]]

 [[0.78573597 0.69699897 0.53824711 ... 0.02874015 0.20607555 0.19174464]
  [0.29461601 0.92052694 0.7281628  ... 0.06167222 0.475073   0.4363058 ]
  [0.31277496 0.14517698 0.3986786  ... 0.81042185 0.37002582 0.90938194]
  ...
  [0.78224069 0.77220974 0.04318761 ... 0.88765731 0.24403219 0.9425377 ]
  [0.9235198  0.02528109 0.55695457 ... 0.357002   0.72393419 0.04957901]
  [0.80874805 0.19504466 0.16204066 ... 0.18101831 0.44133161 0.03108572]]

 [[0.72369079 0.8182676  0.33923842 ... 0.40767163 0.26958999 0.83229979]
  [0.075

If we want to investigate the evoked response (i.e. the average response across trials and sensors), we can use the `mean` method.

In [9]:
evoked = np.mean(arr, axis=(0, 1))
print(evoked.shape)

(200,)


**Q:** What happend to the dimensions of the array? **A:**

Let's say we want to calculate the evoked response for a specific sensor. Then we need to first select the sensor dimension, and then calculate the mean across the trial dimension.

In [10]:
arr_sens_1 = arr[:, 0, :]
print(arr_sens_1.shape)

evoked_sens_1 = np.mean(arr_sens_1, axis=0)
print(evoked_sens_1.shape)

(50, 200)
(200,)
